export const workItems = [
  {
    heading: "Depósito San Antonio Website",
    imgsrc: "/deposito.webp",
    link: "https://www.depositosanantonio.com/",
    github: "https://github.com/francwow/DepositoSanAntonio-Website",
    id: 0,
    languages: "HTML | CSS",
  },
  {
    heading: "Latiendo Website",
    imgsrc: "/latiendo.webp",
    link: "https://www.latiendo.co/",
    github: "https://github.com/francwow/latiendo",
    id: 1,
    languages: "HTML | CSS | JavaScript",
  },
  {
    heading: "Flag Finder webapp",
    imgsrc: "/flagFinder.webp",
    link: "https://flag-finder.vercel.app/",
    github: "https://github.com/francwow/flag-finder",
    id: 2,
    languages: "React | CSS",
  },
  {
    heading: "Eloquent Javascript Exercises",
    imgsrc: "/eloquentjs.webp",
    link: "https://eloquent-java-script.vercel.app/",
    github: "https://github.com/francwow/Eloquent-JavaScript",
    id: 3,
    languages: "HTML | CSS | JavaScript",
  },
  {
    heading: "Responsive Design Exercise",
    imgsrc: "/franos.webp",
    link: "https://franos-website.vercel.app/",
    github: "https://github.com/francwow/franos-website",
    id: 4,
    languages: "HTML | CSS | JavaScript",
  },
  {
    heading: "Arthas Menethil tribute page",
    imgsrc: "/arthas.webp",
    link: "https://arthas-menethil.vercel.app/",
    github: "https://github.com/francwow/Arthas-Menethil",
    id: 5,
    languages: "HTML | CSS | JavaScript",
  },
  {
    heading: "First Portfolio Website",
    imgsrc: "/fos.webp",
    link: "https://francwow.github.io/",
    github: "https://github.com/francwow/francwow.github.io",
    id: 6,
    languages: "HTML | CSS",
  },
];
